// This file is auto-generated by scripts/generate-github-config.js
// Do not edit this file directly. Edit yaal.config.yaml instead.

export const githubConfig = {
  url: 'https://github.com/0xWelt/yaal',
  owner: '0xWelt',
  repo: 'yaal',
  title: 'Yet Another Awesome List',
  description: 'A meta awesome list of awesome lists',
};

export const siteConfig = {
  title: 'Yet Another Awesome List',
  description: 'A meta awesome list of awesome lists',
  url: 'https://0xWelt.github.io/yaal/',
};
