name: Smart Build and Deploy Website

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      should-build: ${{ steps.check.outputs.build-needed }}
      build-reason: ${{ steps.check.outputs.build-reason }}
      changed-files: ${{ steps.check.outputs.changed-files }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Get full history

      - name: Check if build is needed
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Define file patterns to monitor
          PATTERNS="README.md|app/|components/|scripts/|package.json|package-lock.json|next.config.mjs|tsconfig.json|tailwind.config.js|.github/workflows/|yaal.config.yaml"

          # Define detailed file categories
          README_PATTERN="README.md"
          APP_PATTERN="^app/"
          COMPONENTS_PATTERN="^components/"
          SCRIPTS_PATTERN="^scripts/"
          CONFIG_PATTERN="(package\.json|package-lock\.json|next\.config\.js|tsconfig\.json|tailwind\.config\.js)"
          WORKFLOW_PATTERN="^\.github/workflows/"

          # Use GitHub API to find last successful build-and-deploy commit
          echo "🔍 Querying last successful build-and-deploy commit..."

          # Get last successful build-and-deploy workflow run
          RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/smart-deploy.yml/runs?status=success&per_page=1&branch=main")

          LAST_BUILD_SHA=$(echo "$RESPONSE" | jq -r '.workflow_runs[0].head_sha // empty')

          if [ -z "$LAST_BUILD_SHA" ] || [ "$LAST_BUILD_SHA" = "null" ]; then
            echo "🚀 First build - no previous successful build found"
            echo "build-reason=First build - no previous successful build found" >> $GITHUB_OUTPUT
            echo "changed-files=All files (first build)" >> $GITHUB_OUTPUT
            BUILD_NEEDED=true
          else
            echo "📊 Last successful build: $LAST_BUILD_SHA"
            
            # Get list of changed files
            CHANGED_FILES=$(git diff --name-only $LAST_BUILD_SHA HEAD)
            
            if [ -z "$CHANGED_FILES" ]; then
              echo "✅ No file changes"
              echo "build-reason=No file changes" >> $GITHUB_OUTPUT
              echo "changed-files=None" >> $GITHUB_OUTPUT
              BUILD_NEEDED=false
            else
              echo "📁 Detected changed files:"
              echo "$CHANGED_FILES" | while read -r file; do
                echo "  - $file"
              done
              
              # Analyze matching files
              MATCHING_FILES=""
              README_CHANGED=false
              APP_CHANGED=false
              COMPONENTS_CHANGED=false
              SCRIPTS_CHANGED=false
              CONFIG_CHANGED=false
              WORKFLOW_CHANGED=false
              
              while IFS= read -r file; do
                if echo "$file" | grep -qE "$README_PATTERN"; then
                  README_CHANGED=true
                  MATCHING_FILES="$MATCHING_FILES README"
                elif echo "$file" | grep -qE "$APP_PATTERN"; then
                  APP_CHANGED=true
                  MATCHING_FILES="$MATCHING_FILES APP"
                elif echo "$file" | grep -qE "$COMPONENTS_PATTERN"; then
                  COMPONENTS_CHANGED=true
                  MATCHING_FILES="$MATCHING_FILES COMPONENTS"
                elif echo "$file" | grep -qE "$SCRIPTS_PATTERN"; then
                  SCRIPTS_CHANGED=true
                  MATCHING_FILES="$MATCHING_FILES SCRIPTS"
                elif echo "$file" | grep -qE "$CONFIG_PATTERN"; then
                  CONFIG_CHANGED=true
                  MATCHING_FILES="$MATCHING_FILES CONFIG"
                elif echo "$file" | grep -qE "$WORKFLOW_PATTERN"; then
                  WORKFLOW_CHANGED=true
                  MATCHING_FILES="$MATCHING_FILES WORKFLOW"
                fi
              done <<< "$CHANGED_FILES"
              
              # Build detailed reason
              REASON="Changes detected:"
              [ "$README_CHANGED" = true ] && REASON="$REASON README.md"
              [ "$APP_CHANGED" = true ] && REASON="$REASON app files"
              [ "$COMPONENTS_CHANGED" = true ] && REASON="$REASON component files"
              [ "$SCRIPTS_CHANGED" = true ] && REASON="$REASON script files"
              [ "$CONFIG_CHANGED" = true ] && REASON="$REASON config files"
              [ "$WORKFLOW_CHANGED" = true ] && REASON="$REASON workflow files"
              
              # Check if matching files exist
              if [ -n "$MATCHING_FILES" ]; then
                echo "🔍 Matched file types requiring rebuild: $MATCHING_FILES"
                echo "build-reason=$REASON" >> $GITHUB_OUTPUT
                echo "changed-files=$(echo "$CHANGED_FILES" | head -20 | sed ':a;N;$!ba;s/\n/, /g')" >> $GITHUB_OUTPUT
                BUILD_NEEDED=true
              else
                echo "ℹ️  Changed files do not affect build"
                echo "build-reason=Changed files do not affect build" >> $GITHUB_OUTPUT
                echo "changed-files=$(echo "$CHANGED_FILES" | head -10 | sed ':a;N;$!ba;s/\n/, /g')" >> $GITHUB_OUTPUT
                BUILD_NEEDED=false
              fi
            fi
          fi

          echo "build-needed=$BUILD_NEEDED" >> $GITHUB_OUTPUT
          echo "Final decision: Build needed = $BUILD_NEEDED"

  build-and-deploy:
    needs: check-changes
    if: needs.check-changes.outputs.should-build == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate configuration
        run: node scripts/generate-github-config.js

      - name: Parse README and generate data
        run: npm run parse-readme

      - name: Build website
        run: npm run build

      - name: Build Summary
        run: |
          echo "## 📋 Build Details" >> $GITHUB_STEP_SUMMARY
          echo "- **Build Reason**: ${{ needs.check-changes.outputs.build-reason }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Changed Files**: ${{ needs.check-changes.outputs.changed-files }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Build Time**: $(date)" >> $GITHUB_STEP_SUMMARY
          echo "- **Node Version**: $(node --version)" >> $GITHUB_STEP_SUMMARY
          echo "- **NPM Version**: $(npm --version)" >> $GITHUB_STEP_SUMMARY

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  skip-build:
    needs: check-changes
    if: needs.check-changes.outputs.should-build == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Skip build notification
        run: |
          echo "## ⏭️ Skip Build" >> $GITHUB_STEP_SUMMARY
          echo "- **Skip Reason**: ${{ needs.check-changes.outputs.build-reason }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Changed Files**: ${{ needs.check-changes.outputs.changed-files }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Check Time**: $(date)" >> $GITHUB_STEP_SUMMARY
          echo "✅ Detected changed files do not affect website build, skipping deployment"
